### ISSUE TITLE
how to disable update of timestamp whenever i change the file content

### ISSUE THREAD

**Issue by leehin** [lpubsppop01/vscode-auto-timestamp#8]
i notice that the timestamp was change every time i change the file content, and not yet save the file.
This behaviour affect the undo and redo history
How to disable timestamp changes upon change of file content, i only want to timestamp when i save the file

**Comment by migrassi** [comment]
Same problem here! Works ok in my Linux VScode (change only when I save the file) but in Windows the Last modified field change with each single change to the file content.

**Comment by lpubsppop01** [comment]
Hi, @leehin, @migrassi.
Thank you for your feedback, and I'm sorry for the very slow response.

It seems to happen when VS Code's Auto Save is enabled and its setting is `afterDelay`.
You can avoid the issue by turning off Auto Save or setting it to something other than `afterDelay`.
I've confirmed that the extension can break the process in case of AfterDelay, so I'd like to release a fixed version when I have time.

In addition to the above, since this extension works at the timing of `onWillSaveTextDocument`, so it may be affected by other extensions that automatically save.

**Comment by migrassi** [comment]
Thamks a lot, @lpubsppop01. The extension works fine now, with Visual Studio Auto Save option set as ``OnWindowChange``.
